rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ree
  - rbx-18mode
  - rbx-19mode
  - jruby

gemfile:
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile

script: "bundle exec rake test"

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: ree
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: rbx-18mode
      gemfile: gemfiles/rails_4_0.gemfile
